/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Salon;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;

import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;
import static spark.Spark.*;

public class App {

    public static void main(String[] args) {
        staticFileLocation("/public");
        String layout = "templates/layout.vtl";

        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<>();

            model.put("template", "templates/index.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        get("/stylists/new", (request, response) -> {
            Map<String, Object> model = new HashMap<>();
            model.put("template", "templates/stylist-form.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        post("/stylists", (request, response) -> {
            Map<String, Object> model = new HashMap<>();
            String name = request.queryParams("name");
            String phoneNumber = request.queryParams("phoneNumber");
            Stylist newStylist = new Stylist(name, phoneNumber);

            model.put("stylists", Stylist.all());
            model.put("template", "templates/stylists.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        get("/stylists", (request, response) -> {
            Map<String, Object> model = new HashMap<>();
            model.put("stylists", Stylist.all());
            model.put("template", "templates/stylists.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        get("/stylists/:id", (request, response) -> {
            Map<String, Object> model = new HashMap<>();
            Stylist stylist = Stylist.find(Integer.parseInt(request.params(":id")));
            model.put("stylist", stylist);
            model.put("template", "templates/stylist.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        get("clients/new", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/client-form.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        post("/clients", (request, response) -> {
            Map<String, Object> model = new HashMap<>();

            ArrayList<Client> clients = request.session().attribute("clients");
            if (clients == null) {
                clients = new ArrayList<>();
                request.session().attribute("clients", clients);
            }

            String name =request.queryParams("name");
            String phoneNumber = request.queryParams("phoneNumber");
            String service = request.queryParams("service");
            String date = request.queryParams("date");

            Client newClient = new Client(name, phoneNumber, service, date);
            clients.add(newClient);
//            request.session().attribute("client", newClient);

            model.put("clients", request.session().attribute("clients"));
            model.put("template", "templates/clients.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        get("/clients", (request, response) -> {
            Map<String, Object> model = new HashMap<>();

            model.put("clients", request.session().attribute("clients"));
            model.put("template", "templates/clients.vtl");
            return new ModelAndView(model, layout);

        }, new VelocityTemplateEngine());

    }
}
